# Generated by Django 4.0.4 on 2022-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
